export const newPdfStyles = {
  heading: {
    fontSize: 16,
    bold: true,
    alignment: 'left',
    margin: [0, 0, 0, 50],
    color: '#386384',
  },
  columnHeader: {
    fontSize: 11,
    bold: true,
    color: '#4B5157',
    margin: [0, 2.5, 50, 0],
  },
  firstNameHeader: {
    fontSize: 10,
    bold: true,
    color: '#4B5157',
    margin: [0, 5, 60, 5],
  },
  columnText: {
    fontSize: 11,
    bold: true,
    color: '#040404',
    margin: [0, 2.5, 50, 5],
  },
  employeeTableHeader: {
    fontSize: 10,
    bold: true,
    fillColor: '#518EBD',
    margin: [0, 0, 0, 0],
    color: 'white',
    alignment: 'center',
  },
  employeeTableData: {
    fontSize: 9,
    bold: true,
    color: '#040404',
    margin: [0, 0, 0, 5],
    alignment: 'center',
  },
  lastRowTotal: {
    fontSize: 12,
    bold: true,
    fillColor: '#DFEEF9',
    margin: [0, 0, 16, 0],
    color: 'black',
    alignment: 'center',
  },
  dailyTotalValues: {
    fontSize: 11,
    bold: true,
    color: 'black',
    margin: [0, 0, 10, 5],
    alignment: 'center',
  },
  weeklyTotalRow: {
    fontSize: 9,
    bold: true,
    color: '#040404',
    margin: [0, 0, 0, 5],
    alignment: 'center',
    fillColor: '#beddf3',
  },
};
